replacements = {
    "accoglienza": "#accoglienza",
    "supporto psicologico": "#supportopsicologico",
    "supporto legale": "#supportolegale",
    "Ospitalità ": "#ospitalita",
    "alloggio": "#alloggio",
    "alloggi": "#alloggi",
    "assistenza sanitaria ": "#assistenzasanitaria",
    "bambini": "#bambini",
    "minori": "#minori",
    "donne": "#donne",
    "lavoro": "#lavoro",
    "richiesta di aiuto": "#richiestadiaiuto",
    "scuola": "#scuola",
    "mediazione linguistica ": "#mediazionelinguistica",
    "mediatori linguistici": "#mediatorilinguistici",
    "raccolta beni": "#raccoltabeni",
    "raccolte beni": "#raccoltebeni",
    "raccolta fondi": "#raccoltafondi",
    "raccolte fondi": "#raccoltefondi",
    "farmaci": "#farmaci",
    "medicine": "#medicine",
    "donazioni": "#donazioni",
    "risorse utili": "#risorseutili",
    "fake news": "#fakenews",
    "fact cheking": "#factchecking",
    "bufale": "#bufale",
    "truffe": "#truffe",
    "volontari": "#volontari",
}
