replacements = {
    "accoglienza": "#accoglienza",
    "supporto psicologico": "#supportopsicologico",
    "supporto legale": "#supportolegale",
    "assistenza legale": "#assistenzalegale",
    "ospitalità": "#ospitalita",
    "alloggio": "#alloggio",
    "alloggi": "#alloggi",
    "assistenza sanitaria": "#assistenzasanitaria",
    "bambini": "#bambini",
    "minori": "#minori",
    "donne": "#donne",
    "mamme": "#mamme",
    "lavoro": "#lavoro",
    "richiesta di aiuto": "#richiestadiaiuto",
    "scuola": "#scuola",
    "scuole": "#scuole",
    "mediazione linguistica": "#mediazionelinguistica",
    "mediazione culturale": "#mediazioneculturale",
    "mediatori linguistici": "#mediatorilinguistici",
    "mediatori culturali": "#mediatoriculturali",
    "mediatori": "#mediatori",
    "traduttori": "#traduttori",
    "interpreti": "#interpreti",
    "raccolta beni": "#raccoltabeni",
    "raccolta di beni": "#raccoltabeni",
    "raccolte di beni": "#raccoltebeni",
    "raccolte beni": "#raccoltebeni",
    "raccolta fondi": "#raccoltafondi",
    "raccolte fondi": "#raccoltefondi",
    "raccolte di fondi": "#raccoltefondi",
    "raccolta di fondi": "#raccoltafondi",
    "fundraising": "#fundraising",
    "farmaci": "#farmaci",
    "medicine": "#medicine",
    "donazioni": "#donazioni",
    "risorse utili": "#risorseutili",
    "fake news": "#fakenews",
    "fact cheking": "#factchecking",
    "bufale": "#bufale",
    "truffe": "#truffe",
    "volontari": "#volontari",
    "disabilità": "#disabilita",
    "disabili": "#disabili",
    "Lgbtq": "#lgbtq",
    "lgbtq": "#lgbtq",
    "Lgbtqi": "#lgbtqi",
    "lgbtqi": "#lgbtqi",
    "corso": "#corso",
    "corsi": "#corsi",
    "lezioni": "#lezioni",
    "consolato": "#consolato",
    "ambasciata": "#ambasciata",
    "consolati": "#consolati",
    "trasporto": "#tradporto",
    "trasporti": "#trasporti",
    "bus": "#bus",
    "autobus": "#autobus",
    "studenti": "#studenti",
    "permesso di soggiorno": "#permessodisoggiorno"
}
